/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.una.MetodosOrdenacao.Janelas;

/**
 *
 * @author 31322163
 */
public class NovoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NovoJFrame
     */
    public NovoJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsPanel = new javax.swing.JPanel();
        botaoCres = new javax.swing.JButton();
        botaoDec = new javax.swing.JButton();
        botaoAleat = new javax.swing.JButton();
        resultsPanel = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        select_title = new javax.swing.JLabel();
        insert_title = new javax.swing.JLabel();
        bouble_title = new javax.swing.JLabel();
        quick_title = new javax.swing.JLabel();
        n10_title = new javax.swing.JLabel();
        selec_10 = new javax.swing.JLabel();
        insert_10 = new javax.swing.JLabel();
        bouble_10 = new javax.swing.JLabel();
        Quick_10 = new javax.swing.JLabel();
        n100_title = new javax.swing.JLabel();
        select_100 = new javax.swing.JLabel();
        insert_100 = new javax.swing.JLabel();
        bouble_100 = new javax.swing.JLabel();
        quick_100 = new javax.swing.JLabel();
        n1000_title = new javax.swing.JLabel();
        select_1000 = new javax.swing.JLabel();
        insert_1000 = new javax.swing.JLabel();
        bouble_1000 = new javax.swing.JLabel();
        quick_1000 = new javax.swing.JLabel();
        n10000_title = new javax.swing.JLabel();
        select_10000 = new javax.swing.JLabel();
        insert_10000 = new javax.swing.JLabel();
        bouble_10000 = new javax.swing.JLabel();
        quick_10000 = new javax.swing.JLabel();
        statusPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Métodos de Ordenação");
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setName("JanelaPrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 500));

        buttonsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botaoCres.setText("Gerar Crescente");
        botaoCres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCresActionPerformed(evt);
            }
        });

        botaoDec.setText("Gerar Decrescente");
        botaoDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDecActionPerformed(evt);
            }
        });

        botaoAleat.setText("Gerar Aleatório");
        botaoAleat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAleatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoCres, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(botaoDec, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(botaoAleat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(botaoCres)
                    .addComponent(botaoDec)
                    .addComponent(botaoAleat))
                .addGap(15, 15, 15))
        );

        resultsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        resultsPanel.setLayout(new java.awt.GridLayout(5, 0, 0, 5));

        labelTitle.setBackground(new java.awt.Color(255, 255, 255));
        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(153, 153, 153));
        labelTitle.setText("<html>\nTamanho vetor/<br>Tipo de Ordenação\n</html>");
        resultsPanel.add(labelTitle);

        select_title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        select_title.setText("Selection Sort");
        resultsPanel.add(select_title);

        insert_title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        insert_title.setText("Insertion Sort");
        resultsPanel.add(insert_title);

        bouble_title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bouble_title.setText("Bouble Sorte");
        resultsPanel.add(bouble_title);

        quick_title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        quick_title.setText("Quick Sort");
        resultsPanel.add(quick_title);

        n10_title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        n10_title.setText("10");
        resultsPanel.add(n10_title);

        selec_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selec_10.setText("? valor ?");
        selec_10.setToolTipText("");
        selec_10.setName("select_"); // NOI18N
        resultsPanel.add(selec_10);

        insert_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        insert_10.setText("? valor ?");
        insert_10.setToolTipText("");
        insert_10.setName("insert_"); // NOI18N
        resultsPanel.add(insert_10);

        bouble_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bouble_10.setText("? valor ?");
        bouble_10.setToolTipText("");
        bouble_10.setName("bouble_"); // NOI18N
        resultsPanel.add(bouble_10);

        Quick_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quick_10.setText("? valor ?");
        Quick_10.setToolTipText("");
        Quick_10.setName("quick_"); // NOI18N
        resultsPanel.add(Quick_10);

        n100_title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        n100_title.setText("100");
        resultsPanel.add(n100_title);

        select_100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        select_100.setText("? valor ?");
        select_100.setToolTipText("");
        select_100.setName("select_"); // NOI18N
        resultsPanel.add(select_100);

        insert_100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        insert_100.setText("? valor ?");
        insert_100.setToolTipText("");
        insert_100.setName("insert_"); // NOI18N
        resultsPanel.add(insert_100);

        bouble_100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bouble_100.setText("? valor ?");
        bouble_100.setToolTipText("");
        bouble_100.setName("bouble_"); // NOI18N
        resultsPanel.add(bouble_100);

        quick_100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quick_100.setText("? valor ?");
        quick_100.setToolTipText("");
        quick_100.setName("quick_"); // NOI18N
        resultsPanel.add(quick_100);

        n1000_title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        n1000_title.setText("1000");
        resultsPanel.add(n1000_title);

        select_1000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        select_1000.setText("? valor ?");
        select_1000.setToolTipText("");
        select_1000.setName("select_"); // NOI18N
        resultsPanel.add(select_1000);

        insert_1000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        insert_1000.setText("? valor ?");
        insert_1000.setToolTipText("");
        insert_1000.setName("insert_"); // NOI18N
        resultsPanel.add(insert_1000);

        bouble_1000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bouble_1000.setText("? valor ?");
        bouble_1000.setToolTipText("");
        bouble_1000.setName("bouble_"); // NOI18N
        resultsPanel.add(bouble_1000);

        quick_1000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quick_1000.setText("? valor ?");
        quick_1000.setToolTipText("");
        quick_1000.setName("quick_"); // NOI18N
        resultsPanel.add(quick_1000);

        n10000_title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        n10000_title.setText("10000");
        resultsPanel.add(n10000_title);

        select_10000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        select_10000.setText("? valor ?");
        select_10000.setToolTipText("");
        select_10000.setName("select_"); // NOI18N
        resultsPanel.add(select_10000);

        insert_10000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        insert_10000.setText("? valor ?");
        insert_10000.setToolTipText("");
        insert_10000.setName("insert_"); // NOI18N
        resultsPanel.add(insert_10000);

        bouble_10000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bouble_10000.setText("? valor ?");
        bouble_10000.setToolTipText("");
        bouble_10000.setName("bouble_"); // NOI18N
        resultsPanel.add(bouble_10000);

        quick_10000.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quick_10000.setText("? valor ?");
        quick_10000.setToolTipText("");
        quick_10000.setName("quick_"); // NOI18N
        resultsPanel.add(quick_10000);

        statusPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        statusLabel.setForeground(new java.awt.Color(153, 153, 153));
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Status irá aparecer aqui");

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPanelLayout.createSequentialGroup()
                .addComponent(statusLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCresActionPerformed

    private void botaoDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDecActionPerformed

    private void botaoAleatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAleatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAleatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Quick_10;
    private javax.swing.JButton botaoAleat;
    private javax.swing.JButton botaoCres;
    private javax.swing.JButton botaoDec;
    private javax.swing.JLabel bouble_10;
    private javax.swing.JLabel bouble_100;
    private javax.swing.JLabel bouble_1000;
    private javax.swing.JLabel bouble_10000;
    private javax.swing.JLabel bouble_title;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel insert_10;
    private javax.swing.JLabel insert_100;
    private javax.swing.JLabel insert_1000;
    private javax.swing.JLabel insert_10000;
    private javax.swing.JLabel insert_title;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel n10000_title;
    private javax.swing.JLabel n1000_title;
    private javax.swing.JLabel n100_title;
    private javax.swing.JLabel n10_title;
    private javax.swing.JLabel quick_100;
    private javax.swing.JLabel quick_1000;
    private javax.swing.JLabel quick_10000;
    private javax.swing.JLabel quick_title;
    private javax.swing.JPanel resultsPanel;
    private javax.swing.JLabel selec_10;
    private javax.swing.JLabel select_100;
    private javax.swing.JLabel select_1000;
    private javax.swing.JLabel select_10000;
    private javax.swing.JLabel select_title;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables
}
